# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quin.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_APPwithLNK(object):
    def setupUi(self, APPwithLNK):
        APPwithLNK.setObjectName("APPwithLNK")
        APPwithLNK.resize(400, 654)
        self.centralwidget = QtWidgets.QWidget(APPwithLNK)
        self.centralwidget.setObjectName("centralwidget")
        self.edit_input = QtWidgets.QTextEdit(self.centralwidget)
        self.edit_input.setGeometry(QtCore.QRect(130, 110, 251, 191))
        self.edit_input.setObjectName("edit_input")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-20, 350, 451, 31))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 590, 331, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_received = QtWidgets.QLabel(self.layoutWidget)
        self.label_received.setObjectName("label_received")
        self.horizontalLayout_3.addWidget(self.label_received)
        self.num_received = QtWidgets.QLCDNumber(self.layoutWidget)
        self.num_received.setObjectName("num_received")
        self.horizontalLayout_3.addWidget(self.num_received)
        self.label_failed = QtWidgets.QLabel(self.layoutWidget)
        self.label_failed.setObjectName("label_failed")
        self.horizontalLayout_3.addWidget(self.label_failed)
        self.num_failed = QtWidgets.QLCDNumber(self.layoutWidget)
        self.num_failed.setObjectName("num_failed")
        self.horizontalLayout_3.addWidget(self.num_failed)
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(30, 320, 331, 25))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_total_send = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_total_send.setObjectName("label_total_send")
        self.horizontalLayout_5.addWidget(self.label_total_send)
        self.num_total_send = QtWidgets.QLCDNumber(self.layoutWidget_2)
        self.num_total_send.setObjectName("num_total_send")
        self.horizontalLayout_5.addWidget(self.num_total_send)
        self.label_total_resend = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_total_resend.setObjectName("label_total_resend")
        self.horizontalLayout_5.addWidget(self.label_total_resend)
        self.num_total_resend = QtWidgets.QLCDNumber(self.layoutWidget_2)
        self.num_total_resend.setObjectName("num_total_resend")
        self.horizontalLayout_5.addWidget(self.num_total_resend)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(-20, 80, 451, 31))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(22, 109, 100, 100))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_auto_send = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_auto_send.setObjectName("btn_auto_send")
        self.verticalLayout.addWidget(self.btn_auto_send)
        self.btn_stop_send = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_stop_send.setObjectName("btn_stop_send")
        self.verticalLayout.addWidget(self.btn_stop_send)
        self.btn_send_once = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_send_once.setObjectName("btn_send_once")
        self.verticalLayout.addWidget(self.btn_send_once)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(24, 380, 101, 100))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_print_bit = QtWidgets.QPushButton(self.layoutWidget2)
        self.btn_print_bit.setObjectName("btn_print_bit")
        self.verticalLayout_2.addWidget(self.btn_print_bit)
        self.btn_print_byte = QtWidgets.QPushButton(self.layoutWidget2)
        self.btn_print_byte.setObjectName("btn_print_byte")
        self.verticalLayout_2.addWidget(self.btn_print_byte)
        self.btn_stop_print = QtWidgets.QPushButton(self.layoutWidget2)
        self.btn_stop_print.setObjectName("btn_stop_print")
        self.verticalLayout_2.addWidget(self.btn_stop_print)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(130, 380, 251, 191))
        self.textBrowser.setObjectName("textBrowser")
        self.label_icon = QtWidgets.QLabel(self.centralwidget)
        self.label_icon.setGeometry(QtCore.QRect(40, 40, 151, 16))
        self.label_icon.setObjectName("label_icon")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(231, 21, 138, 55))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_port = QtWidgets.QLabel(self.widget)
        self.label_port.setObjectName("label_port")
        self.gridLayout.addWidget(self.label_port, 0, 0, 1, 1)
        self.num_port = QtWidgets.QLCDNumber(self.widget)
        self.num_port.setProperty("value", 0.0)
        self.num_port.setObjectName("num_port")
        self.gridLayout.addWidget(self.num_port, 0, 1, 1, 1)
        self.label_iworkmode = QtWidgets.QLabel(self.widget)
        self.label_iworkmode.setObjectName("label_iworkmode")
        self.gridLayout.addWidget(self.label_iworkmode, 1, 0, 1, 1)
        self.num_iworkmode = QtWidgets.QLCDNumber(self.widget)
        self.num_iworkmode.setObjectName("num_iworkmode")
        self.gridLayout.addWidget(self.num_iworkmode, 1, 1, 1, 1)
        APPwithLNK.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(APPwithLNK)
        self.statusbar.setObjectName("statusbar")
        APPwithLNK.setStatusBar(self.statusbar)

        self.retranslateUi(APPwithLNK)
        QtCore.QMetaObject.connectSlotsByName(APPwithLNK)

    def retranslateUi(self, APPwithLNK):
        _translate = QtCore.QCoreApplication.translate
        APPwithLNK.setWindowTitle(_translate("APPwithLNK", "DogHeadFish"))
        self.edit_input.setPlaceholderText(_translate("APPwithLNK", "Write someting in range the of ascii."))
        self.label_received.setText(_translate("APPwithLNK", "     Received"))
        self.label_failed.setText(_translate("APPwithLNK", "         Failed"))
        self.label_total_send.setText(_translate("APPwithLNK", "Total Send"))
        self.label_total_resend.setText(_translate("APPwithLNK", "Total Resend"))
        self.btn_auto_send.setText(_translate("APPwithLNK", "Auto Send"))
        self.btn_stop_send.setText(_translate("APPwithLNK", "Stop Auto Send"))
        self.btn_send_once.setText(_translate("APPwithLNK", "Send Once"))
        self.btn_print_bit.setText(_translate("APPwithLNK", "Print Data Bit"))
        self.btn_print_byte.setText(_translate("APPwithLNK", "Print Data Byte"))
        self.btn_stop_print.setText(_translate("APPwithLNK", "Stop Printing"))
        self.textBrowser.setPlaceholderText(_translate("APPwithLNK", "Received data will be ploted here."))
        self.label_icon.setText(_translate("APPwithLNK", "\"Should be an icon here.\""))
        self.label_port.setText(_translate("APPwithLNK", "   PORT"))
        self.label_iworkmode.setText(_translate("APPwithLNK", "Work Mode"))

