# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'client.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Client(object):
    def setupUi(self, Client):
        Client.setObjectName("Client")
        Client.resize(400, 623)
        self.centralwidget = QtWidgets.QWidget(Client)
        self.centralwidget.setObjectName("centralwidget")
        self.edit_input = QtWidgets.QTextEdit(self.centralwidget)
        self.edit_input.setGeometry(QtCore.QRect(130, 80, 251, 191))
        self.edit_input.setObjectName("edit_input")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-20, 320, 451, 31))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(30, 290, 331, 25))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_total_send = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_total_send.setObjectName("label_total_send")
        self.horizontalLayout_5.addWidget(self.label_total_send)
        self.num_total_send = QtWidgets.QLCDNumber(self.layoutWidget_2)
        self.num_total_send.setObjectName("num_total_send")
        self.horizontalLayout_5.addWidget(self.num_total_send)
        self.label_total_resend = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_total_resend.setObjectName("label_total_resend")
        self.horizontalLayout_5.addWidget(self.label_total_resend)
        self.num_total_resend = QtWidgets.QLCDNumber(self.layoutWidget_2)
        self.num_total_resend.setObjectName("num_total_resend")
        self.horizontalLayout_5.addWidget(self.num_total_resend)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(-20, 50, 451, 31))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 350, 361, 191))
        self.textBrowser.setObjectName("textBrowser")
        self.label_icon = QtWidgets.QLabel(self.centralwidget)
        self.label_icon.setGeometry(QtCore.QRect(40, 20, 151, 16))
        self.label_icon.setObjectName("label_icon")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 110, 101, 59))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.num_des = QtWidgets.QSpinBox(self.layoutWidget)
        self.num_des.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.num_des.setMaximum(7)
        self.num_des.setObjectName("num_des")
        self.verticalLayout.addWidget(self.num_des)
        self.btn_send = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_send.setObjectName("btn_send")
        self.verticalLayout.addWidget(self.btn_send)
        self.label_des = QtWidgets.QLabel(self.centralwidget)
        self.label_des.setGeometry(QtCore.QRect(30, 80, 81, 20))
        self.label_des.setObjectName("label_des")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(260, 20, 105, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_id = QtWidgets.QLabel(self.widget)
        self.label_id.setObjectName("label_id")
        self.horizontalLayout.addWidget(self.label_id)
        self.num_id = QtWidgets.QLCDNumber(self.widget)
        self.num_id.setProperty("value", 0.0)
        self.num_id.setObjectName("num_id")
        self.horizontalLayout.addWidget(self.num_id)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(30, 560, 340, 30))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_received = QtWidgets.QLabel(self.widget1)
        self.label_received.setObjectName("label_received")
        self.horizontalLayout_2.addWidget(self.label_received)
        self.num_received = QtWidgets.QLCDNumber(self.widget1)
        self.num_received.setObjectName("num_received")
        self.horizontalLayout_2.addWidget(self.num_received)
        self.label_failed = QtWidgets.QLabel(self.widget1)
        self.label_failed.setObjectName("label_failed")
        self.horizontalLayout_2.addWidget(self.label_failed)
        self.num_failed = QtWidgets.QLCDNumber(self.widget1)
        self.num_failed.setObjectName("num_failed")
        self.horizontalLayout_2.addWidget(self.num_failed)
        self.btn_cln = QtWidgets.QPushButton(self.widget1)
        self.btn_cln.setObjectName("btn_cln")
        self.horizontalLayout_2.addWidget(self.btn_cln)
        Client.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Client)
        self.statusbar.setObjectName("statusbar")
        Client.setStatusBar(self.statusbar)

        self.retranslateUi(Client)
        QtCore.QMetaObject.connectSlotsByName(Client)

    def retranslateUi(self, Client):
        _translate = QtCore.QCoreApplication.translate
        Client.setWindowTitle(_translate("Client", "Client"))
        self.edit_input.setPlaceholderText(_translate("Client", "Write someting in range the of ascii."))
        self.label_total_send.setText(_translate("Client", "Total Send"))
        self.label_total_resend.setText(_translate("Client", "Total Resend"))
        self.textBrowser.setPlaceholderText(_translate("Client", "Received data will be ploted here."))
        self.label_icon.setText(_translate("Client", "\"Should be an icon here.\""))
        self.btn_send.setText(_translate("Client", "Send"))
        self.label_des.setText(_translate("Client", "Destination ID"))
        self.label_id.setText(_translate("Client", "My ID"))
        self.label_received.setText(_translate("Client", " Received"))
        self.label_failed.setText(_translate("Client", "Failed"))
        self.btn_cln.setText(_translate("Client", "Clear"))

